
BEGIN
  FOR i IN (
    SELECT index_name FROM user_indexes
    WHERE index_name IN (
      'IDX_ROOMS_HOSTEL',
      'IDX_USERS_ROLE',
      'IDX_AUTH_TOKENS_USER',
      'IDX_ISSUES_SUBMITTED','IDX_ISSUES_ASSIGNED','IDX_ISSUES_STATUS',
      'IDX_ISSUES_URGENCY','IDX_ISSUES_ROOM','IDX_ISSUES_CREATED',
      'IDX_PHOTOS_ISSUE',
      'IDX_TIMELINE_ISSUE',
      'IDX_NOTIF_USER','IDX_NOTIF_UNREAD',
      'IDX_AUDIT_RECORD'
    )
  ) LOOP
    EXECUTE IMMEDIATE 'DROP INDEX ' || i.index_name;
  END LOOP;
END;
/

BEGIN
  FOR t IN (
    SELECT table_name FROM user_tables
    WHERE table_name IN (
      'AUDIT_LOG',
      'NOTICES',
      'NOTIFICATIONS',
      'ISSUE_TIMELINE',
      'ISSUE_PHOTOS',
      'ISSUES',
      'AUTH_TOKENS',
      'USERS',
      'ROOMS',
      'HOSTELS'
    )
  ) LOOP
    EXECUTE IMMEDIATE 'DROP TABLE ' || t.table_name || ' CASCADE CONSTRAINTS PURGE';
  END LOOP;
END;
/


BEGIN
  FOR s IN (
    SELECT sequence_name FROM user_sequences
    WHERE sequence_name = 'SEQ_ISSUE_TICKET'
  ) LOOP
    EXECUTE IMMEDIATE 'DROP SEQUENCE ' || s.sequence_name;
  END LOOP;
END;
/

CREATE SEQUENCE seq_issue_ticket
  START WITH 1
  INCREMENT BY 1
  NOCACHE
  NOCYCLE;

CREATE TABLE hostels (
  id          VARCHAR2(36)  DEFAULT SYS_GUID() PRIMARY KEY,
  name        VARCHAR2(100) NOT NULL,
  description VARCHAR2(500),
  created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT uq_hostel_name UNIQUE (name)
);

COMMENT ON TABLE  hostels       IS 'Campus hostel blocks';
COMMENT ON COLUMN hostels.id    IS 'UUID generated by SYS_GUID()';


CREATE TABLE rooms (
  id          VARCHAR2(36)  DEFAULT SYS_GUID() PRIMARY KEY,
  hostel_id   VARCHAR2(36)  NOT NULL,
  room_number VARCHAR2(20)  NOT NULL,
  floor_num   NUMBER(2),
  capacity    NUMBER(2)     DEFAULT 2,
  created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_rooms_hostel    FOREIGN KEY (hostel_id) REFERENCES hostels(id) ON DELETE CASCADE,
  CONSTRAINT uq_room_in_hostel  UNIQUE (hostel_id, room_number)
);

CREATE INDEX idx_rooms_hostel ON rooms(hostel_id);


CREATE TABLE users (
  id              VARCHAR2(36)  DEFAULT SYS_GUID() PRIMARY KEY,
  role            VARCHAR2(10)  NOT NULL,
  reg_number      VARCHAR2(30)  UNIQUE,
  full_name       VARCHAR2(150) NOT NULL,
  email           VARCHAR2(150) NOT NULL,
  phone           VARCHAR2(20),
  password_hash   VARCHAR2(255) NOT NULL,
  avatar_url      VARCHAR2(500),

  -- Student fields
  programme       VARCHAR2(100),
  year_of_study   NUMBER(1),
  room_id         VARCHAR2(36),

  -- Worker fields
  specialisation  VARCHAR2(100),
  is_available    NUMBER(1)     DEFAULT 1,   -- 1=TRUE 0=FALSE

  is_active       NUMBER(1)     DEFAULT 1    NOT NULL,
  last_login_at   TIMESTAMP,
  created_at      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at      TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,

  -- Constraints
  CONSTRAINT chk_user_role
    CHECK (role IN ('student','worker','admin')),
  CONSTRAINT uq_user_email
    UNIQUE (email),
  CONSTRAINT chk_reg_number_format
    CHECK (
      reg_number IS NULL OR
      REGEXP_LIKE(reg_number, '^[a-z]+(/[a-z]+)?/[0-9]{2}/[0-9]{2}$')
    ),
  CONSTRAINT chk_is_available CHECK (is_available IN (0,1)),
  CONSTRAINT chk_is_active    CHECK (is_active    IN (0,1)),
  CONSTRAINT fk_users_room    FOREIGN KEY (room_id) REFERENCES rooms(id) ON DELETE SET NULL
);

-- FIX 2: Removed idx_users_email and idx_users_reg_number — Oracle
--         automatically creates indexes for UNIQUE constraints (ORA-01408).
--         Only idx_users_role is needed as role has no unique constraint.
CREATE INDEX idx_users_role ON users(role);


--  TABLE: AUTH_TOKENS  (JWT refresh tokens)

CREATE TABLE auth_tokens (
  id          VARCHAR2(36)  DEFAULT SYS_GUID() PRIMARY KEY,
  user_id     VARCHAR2(36)  NOT NULL,
  token_hash  VARCHAR2(255) NOT NULL UNIQUE,
  expires_at  TIMESTAMP     NOT NULL,
  revoked     NUMBER(1)     DEFAULT 0 NOT NULL,
  created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_token_user  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT chk_revoked    CHECK (revoked IN (0,1))
);

CREATE INDEX idx_auth_tokens_user ON auth_tokens(user_id);


--  TABLE: ISSUES  (maintenance requests)
CREATE TABLE issues (
  id               VARCHAR2(36)   DEFAULT SYS_GUID() PRIMARY KEY,
  ticket_number    VARCHAR2(20)   NOT NULL UNIQUE,   -- MNT-2024-0001
  submitted_by     VARCHAR2(36)   NOT NULL,
  room_id          VARCHAR2(36)   NOT NULL,
  assigned_to      VARCHAR2(36),
  escalated_to     VARCHAR2(36),

  title            VARCHAR2(200)  NOT NULL,
  description      CLOB,
  category         VARCHAR2(20)   NOT NULL,
  urgency          VARCHAR2(15)   DEFAULT 'medium'  NOT NULL,
  status           VARCHAR2(15)   DEFAULT 'pending' NOT NULL,

  escalated_at     TIMESTAMP,
  escalation_note  VARCHAR2(500),
  deadline         TIMESTAMP,
  resolved_at      TIMESTAMP,

  created_at       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at       TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,

  -- Constraints
  CONSTRAINT chk_issue_category
    CHECK (category IN ('electrical','plumbing','furniture','bathroom','internet','security','other')),
  CONSTRAINT chk_issue_urgency
    CHECK (urgency IN ('low','medium','high','emergency')),
  CONSTRAINT chk_issue_status
    CHECK (status IN ('pending','in_progress','resolved','escalated','cancelled')),
  CONSTRAINT fk_issue_submitted  FOREIGN KEY (submitted_by)  REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_issue_room       FOREIGN KEY (room_id)       REFERENCES rooms(id),
  CONSTRAINT fk_issue_assigned   FOREIGN KEY (assigned_to)   REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_issue_escalated  FOREIGN KEY (escalated_to)  REFERENCES users(id) ON DELETE SET NULL
);

CREATE INDEX idx_issues_submitted  ON issues(submitted_by);
CREATE INDEX idx_issues_assigned   ON issues(assigned_to);
CREATE INDEX idx_issues_status     ON issues(status);
CREATE INDEX idx_issues_urgency    ON issues(urgency);
CREATE INDEX idx_issues_room       ON issues(room_id);
CREATE INDEX idx_issues_created    ON issues(created_at DESC);


--  TABLE: ISSUE_PHOTOS
CREATE TABLE issue_photos (
  id          VARCHAR2(36)  DEFAULT SYS_GUID() PRIMARY KEY,
  issue_id    VARCHAR2(36)  NOT NULL,
  url         VARCHAR2(500) NOT NULL,
  filename    VARCHAR2(255),
  mime_type   VARCHAR2(50),
  size_bytes  NUMBER(10),
  uploaded_by VARCHAR2(36),
  created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_photo_issue    FOREIGN KEY (issue_id)    REFERENCES issues(id) ON DELETE CASCADE,
  CONSTRAINT fk_photo_uploader FOREIGN KEY (uploaded_by) REFERENCES users(id)  ON DELETE SET NULL
);

CREATE INDEX idx_photos_issue ON issue_photos(issue_id);


--  TABLE: ISSUE_TIMELINE
CREATE TABLE issue_timeline (
  id          VARCHAR2(36)  DEFAULT SYS_GUID() PRIMARY KEY,
  issue_id    VARCHAR2(36)  NOT NULL,
  actor_id    VARCHAR2(36),
  event_type  VARCHAR2(80)  NOT NULL,
  note        VARCHAR2(1000),
  created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT fk_timeline_issue FOREIGN KEY (issue_id)  REFERENCES issues(id) ON DELETE CASCADE,
  CONSTRAINT fk_timeline_actor FOREIGN KEY (actor_id)  REFERENCES users(id)  ON DELETE SET NULL
);

CREATE INDEX idx_timeline_issue ON issue_timeline(issue_id);

--  TABLE: NOTIFICATIONS

CREATE TABLE notifications (
  id          VARCHAR2(36)  DEFAULT SYS_GUID() PRIMARY KEY,
  user_id     VARCHAR2(36)  NOT NULL,
  issue_id    VARCHAR2(36),
  notif_type  VARCHAR2(30)  NOT NULL,
  title       VARCHAR2(200) NOT NULL,
  body        VARCHAR2(1000),
  is_read     NUMBER(1)     DEFAULT 0 NOT NULL,
  created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT chk_notif_type
    CHECK (notif_type IN ('request_received','technician_assigned','status_update','resolved','escalated','notice')),
  CONSTRAINT chk_is_read   CHECK (is_read IN (0,1)),
  CONSTRAINT fk_notif_user  FOREIGN KEY (user_id)  REFERENCES users(id)  ON DELETE CASCADE,
  CONSTRAINT fk_notif_issue FOREIGN KEY (issue_id) REFERENCES issues(id) ON DELETE CASCADE
);

CREATE INDEX idx_notif_user   ON notifications(user_id);
CREATE INDEX idx_notif_unread ON notifications(user_id, is_read);

--  TABLE: NOTICES  (hostel-wide announcements)

CREATE TABLE notices (
  id          VARCHAR2(36)  DEFAULT SYS_GUID() PRIMARY KEY,
  posted_by   VARCHAR2(36)  NOT NULL,
  title       VARCHAR2(200) NOT NULL,
  body        CLOB          NOT NULL,
  is_active   NUMBER(1)     DEFAULT 1 NOT NULL,
  expires_at  TIMESTAMP,
  created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT chk_notice_active CHECK (is_active IN (0,1)),
  CONSTRAINT fk_notice_poster  FOREIGN KEY (posted_by) REFERENCES users(id) ON DELETE CASCADE
);

--  TABLE: AUDIT_LOG

CREATE TABLE audit_log (
  id          NUMBER        GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  table_name  VARCHAR2(80)  NOT NULL,
  record_id   VARCHAR2(36)  NOT NULL,
  action      VARCHAR2(10)  NOT NULL,
  actor_id    VARCHAR2(36),
  old_data    CLOB,          -- JSON stored as CLOB
  new_data    CLOB,
  created_at  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT chk_audit_action CHECK (action IN ('INSERT','UPDATE','DELETE'))
);

CREATE INDEX idx_audit_record ON audit_log(table_name, record_id);

CREATE OR REPLACE TRIGGER trg_issue_ticket_number
BEFORE INSERT ON issues
FOR EACH ROW
BEGIN
  :NEW.ticket_number := 'MNT-' || TO_CHAR(SYSTIMESTAMP, 'YYYY') || '-'
                        || LPAD(seq_issue_ticket.NEXTVAL, 4, '0');
END;
/

-- 2. Auto-update updated_at on users
CREATE OR REPLACE TRIGGER trg_users_updated_at
BEFORE UPDATE ON users
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

-- 3. Auto-update updated_at on issues
CREATE OR REPLACE TRIGGER trg_issues_updated_at
BEFORE UPDATE ON issues
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

-- 4. Auto-update updated_at on notices
CREATE OR REPLACE TRIGGER trg_notices_updated_at
BEFORE UPDATE ON notices
FOR EACH ROW
BEGIN
  :NEW.updated_at := SYSTIMESTAMP;
END;
/

-- 5. Auto-add timeline entry when issue status changes
CREATE OR REPLACE TRIGGER trg_issue_status_change
AFTER UPDATE OF status ON issues
FOR EACH ROW
WHEN (OLD.status != NEW.status)
BEGIN
  INSERT INTO issue_timeline (id, issue_id, actor_id, event_type, note)
  VALUES (
    SYS_GUID(),
    :NEW.id,
    :NEW.assigned_to,
    'status_changed',
    'Status changed from ' || :OLD.status || ' to ' || :NEW.status
  );
END;
/

-- Dashboard stats
CREATE OR REPLACE VIEW v_dashboard_stats AS
SELECT
  COUNT(*)                                                        AS total_requests,
  COUNT(CASE WHEN status = 'pending'     THEN 1 END)             AS pending,
  COUNT(CASE WHEN status = 'in_progress' THEN 1 END)             AS in_progress,
  COUNT(CASE WHEN status = 'resolved'
    AND created_at >= TRUNC(SYSTIMESTAMP,'MM') THEN 1 END)       AS resolved_this_month,
  COUNT(CASE WHEN urgency = 'emergency'
    AND status NOT IN ('resolved','cancelled') THEN 1 END)       AS active_emergencies,
  ROUND(AVG(
    CASE WHEN resolved_at IS NOT NULL
    THEN (CAST(resolved_at AS DATE) - CAST(created_at AS DATE)) * 1440
    END
  ))                                                              AS avg_response_time_minutes
FROM issues;

-- Issue queue ordered by urgency
CREATE OR REPLACE VIEW v_issue_queue AS
SELECT
  i.id,
  i.ticket_number,
  i.title,
  i.category,
  i.urgency,
  i.status,
  i.created_at,
  i.deadline,
  r.room_number,
  h.name       AS hostel_name,
  u.full_name  AS submitted_by_name,
  u.reg_number AS submitted_by_reg,
  w.full_name  AS assigned_to_name,
  (SELECT COUNT(*) FROM issue_photos p WHERE p.issue_id = i.id) AS photo_count
FROM issues i
JOIN rooms   r ON r.id = i.room_id
JOIN hostels h ON h.id = r.hostel_id
JOIN users   u ON u.id = i.submitted_by
LEFT JOIN users w ON w.id = i.assigned_to
ORDER BY
  CASE i.urgency
    WHEN 'emergency' THEN 1
    WHEN 'high'      THEN 2
    WHEN 'medium'    THEN 3
    ELSE 4
  END,
  i.created_at ASC;

-- Hostels
MERGE INTO hostels h
USING (SELECT 'HOSTEL-BLOCK-A-0000-000000000001' AS id, 'Block A' AS name FROM dual) src
ON (h.id = src.id)
WHEN NOT MATCHED THEN INSERT (id, name) VALUES (src.id, src.name);

MERGE INTO hostels h
USING (SELECT 'HOSTEL-BLOCK-B-0000-000000000002' AS id, 'Block B' AS name FROM dual) src
ON (h.id = src.id)
WHEN NOT MATCHED THEN INSERT (id, name) VALUES (src.id, src.name);

MERGE INTO hostels h
USING (SELECT 'HOSTEL-BLOCK-C-0000-000000000003' AS id, 'Block C' AS name FROM dual) src
ON (h.id = src.id)
WHEN NOT MATCHED THEN INSERT (id, name) VALUES (src.id, src.name);

MERGE INTO hostels h
USING (SELECT 'HOSTEL-BLOCK-D-0000-000000000004' AS id, 'Block D' AS name FROM dual) src
ON (h.id = src.id)
WHEN NOT MATCHED THEN INSERT (id, name) VALUES (src.id, src.name);

-- Rooms
MERGE INTO rooms r
USING (SELECT 'ROOM-0000-0000-0001-000000000001' AS id FROM dual) src
ON (r.id = src.id)
WHEN NOT MATCHED THEN
  INSERT (id, hostel_id, room_number, floor_num, capacity)
  VALUES ('ROOM-0000-0000-0001-000000000001','HOSTEL-BLOCK-A-0000-000000000001','A101',1,2);

MERGE INTO rooms r
USING (SELECT 'ROOM-0000-0000-0002-000000000002' AS id FROM dual) src
ON (r.id = src.id)
WHEN NOT MATCHED THEN
  INSERT (id, hostel_id, room_number, floor_num, capacity)
  VALUES ('ROOM-0000-0000-0002-000000000002','HOSTEL-BLOCK-A-0000-000000000001','A202',2,2);

MERGE INTO rooms r
USING (SELECT 'ROOM-0000-0000-0003-000000000003' AS id FROM dual) src
ON (r.id = src.id)
WHEN NOT MATCHED THEN
  INSERT (id, hostel_id, room_number, floor_num, capacity)
  VALUES ('ROOM-0000-0000-0003-000000000003','HOSTEL-BLOCK-B-0000-000000000002','B12', 1,3);

MERGE INTO rooms r
USING (SELECT 'ROOM-0000-0000-0004-000000000004' AS id FROM dual) src
ON (r.id = src.id)
WHEN NOT MATCHED THEN
  INSERT (id, hostel_id, room_number, floor_num, capacity)
  VALUES ('ROOM-0000-0000-0004-000000000004','HOSTEL-BLOCK-C-0000-000000000003','C304',3,2);

MERGE INTO rooms r
USING (SELECT 'ROOM-0000-0000-0005-000000000005' AS id FROM dual) src
ON (r.id = src.id)
WHEN NOT MATCHED THEN
  INSERT (id, hostel_id, room_number, floor_num, capacity)
  VALUES ('ROOM-0000-0000-0005-000000000005','HOSTEL-BLOCK-D-0000-000000000004','D405',4,2);

-- Admin
MERGE INTO users u
USING (SELECT 'USER-ADMIN-0000-0000-000000000001' AS id FROM dual) src
ON (u.id = src.id)
WHEN NOT MATCHED THEN
  INSERT (id, role, reg_number, full_name, email, password_hash, is_active)
  VALUES ('USER-ADMIN-0000-0000-000000000001','admin', NULL,
          'Admin User','admin@chanco.ac.mw',
          '$2b$10$placeholderHashForAdminUser00001', 1);

-- Students (CHANCO reg patterns)
MERGE INTO users u
USING (SELECT 'USER-STU-00000-0001-000000000002' AS id FROM dual) src
ON (u.id = src.id)
WHEN NOT MATCHED THEN
  INSERT (id, role, reg_number, full_name, email, programme, year_of_study, room_id, password_hash)
  VALUES ('USER-STU-00000-0001-000000000002','student','bsc/inf/06/24',
          'Chimwemwe Banda','chimwemwe@chanco.ac.mw',
          'BSc Information Systems', 1,
          'ROOM-0000-0000-0002-000000000002',
          '$2b$10$placeholderHashForStudent0000002');

MERGE INTO users u
USING (SELECT 'USER-STU-00000-0002-000000000003' AS id FROM dual) src
ON (u.id = src.id)
WHEN NOT MATCHED THEN
  INSERT (id, role, reg_number, full_name, email, programme, year_of_study, room_id, password_hash)
  VALUES ('USER-STU-00000-0002-000000000003','student','bsc/com/02/24',
          'Takondwa Phiri','takondwa@chanco.ac.mw',
          'BSc Computer Science', 1,
          'ROOM-0000-0000-0004-000000000004',
          '$2b$10$placeholderHashForStudent0000003');

MERGE INTO users u
USING (SELECT 'USER-STU-00000-0003-000000000004' AS id FROM dual) src
ON (u.id = src.id)
WHEN NOT MATCHED THEN
  INSERT (id, role, reg_number, full_name, email, programme, year_of_study, room_id, password_hash)
  VALUES ('USER-STU-00000-0003-000000000004','student','bed/com/01/24',
          'Yankho Mwale','yankho@chanco.ac.mw',
          'BEd Commerce', 1,
          'ROOM-0000-0000-0003-000000000003',
          '$2b$10$placeholderHashForStudent0000004');

MERGE INTO users u
USING (SELECT 'USER-STU-00000-0004-000000000005' AS id FROM dual) src
ON (u.id = src.id)
WHEN NOT MATCHED THEN
  INSERT (id, role, reg_number, full_name, email, programme, year_of_study, room_id, password_hash)
  VALUES ('USER-STU-00000-0004-000000000005','student','bsc/04/24',
          'Kondwani Nkosi','kondwani@chanco.ac.mw',
          'BSc', 1,
          'ROOM-0000-0000-0005-000000000005',
          '$2b$10$placeholderHashForStudent0000005');

-- Workers
MERGE INTO users u
USING (SELECT 'USER-WRK-00000-0001-000000000006' AS id FROM dual) src
ON (u.id = src.id)
WHEN NOT MATCHED THEN
  INSERT (id, role, reg_number, full_name, email, specialisation, is_available, password_hash)
  VALUES ('USER-WRK-00000-0001-000000000006','worker',NULL,
          'James Mkandawire','james@chanco.ac.mw',
          'Electrical', 1,
          '$2b$10$placeholderHashForWorker00000006');

MERGE INTO users u
USING (SELECT 'USER-WRK-00000-0002-000000000007' AS id FROM dual) src
ON (u.id = src.id)
WHEN NOT MATCHED THEN
  INSERT (id, role, reg_number, full_name, email, specialisation, is_available, password_hash)
  VALUES ('USER-WRK-00000-0002-000000000007','worker',NULL,
          'Sarah Gondwe','sarah@chanco.ac.mw',
          'Plumbing', 0,
          '$2b$10$placeholderHashForWorker00000007');

MERGE INTO users u
USING (SELECT 'USER-WRK-00000-0003-000000000008' AS id FROM dual) src
ON (u.id = src.id)
WHEN NOT MATCHED THEN
  INSERT (id, role, reg_number, full_name, email, specialisation, is_available, password_hash)
  VALUES ('USER-WRK-00000-0003-000000000008','worker',NULL,
          'Mark Chirwa','mark@chanco.ac.mw',
          'General', 1,
          '$2b$10$placeholderHashForWorker00000008');

-- Sample Issues  (ticket trigger fires automatically)
INSERT INTO issues (id, submitted_by, room_id, title, description, category, urgency, status, deadline)
  VALUES (SYS_GUID(),
          'USER-STU-00000-0001-000000000002',
          'ROOM-0000-0000-0002-000000000002',
          'Broken Socket',
          'The socket near my study desk is not working. Phone cannot charge.',
          'electrical','high','pending',
          SYSTIMESTAMP + INTERVAL '48' HOUR);

INSERT INTO issues (id, submitted_by, room_id, assigned_to, title, description, category, urgency, status, deadline)
  VALUES (SYS_GUID(),
          'USER-STU-00000-0002-000000000003',
          'ROOM-0000-0000-0004-000000000004',
          'USER-WRK-00000-0001-000000000006',
          'Water Leak',
          'There is a steady water leak under the bathroom sink.',
          'plumbing','medium','in_progress',
          SYSTIMESTAMP + INTERVAL '24' HOUR);

INSERT INTO issues (id, submitted_by, room_id, title, description, category, urgency, status, resolved_at, deadline)
  VALUES (SYS_GUID(),
          'USER-STU-00000-0003-000000000004',
          'ROOM-0000-0000-0003-000000000003',
          'Broken Light',
          'Main room light bulb has gone out.',
          'electrical','low','resolved',
          SYSTIMESTAMP - INTERVAL '2' HOUR,
          SYSTIMESTAMP - INTERVAL '1' DAY);

COMMIT;

-- =============================================================
--  REFERENCE QUERIES FOR NESTJS BACKEND
-- =============================================================
/*
-- 1. Login: find active user by email
SELECT * FROM users
WHERE email = 'chimwemwe@chanco.ac.mw' AND is_active = 1;

-- 2. Validate CHANCO reg number format
SELECT * FROM users
WHERE reg_number = 'bsc/inf/06/24';

-- 3. Get all issues submitted by a student
SELECT * FROM v_issue_queue
WHERE submitted_by_reg = 'bsc/inf/06/24';

-- 4. Dashboard stats
SELECT * FROM v_dashboard_stats;

-- 5. All open issues ordered by urgency
SELECT * FROM v_issue_queue
WHERE status NOT IN ('resolved','cancelled');

-- 6. Issues from a specific room
SELECT i.* FROM issues i
JOIN rooms r ON r.id = i.room_id
WHERE r.room_number = 'A202';

-- 7. Assign a worker to an issue
UPDATE issues
SET assigned_to = 'USER-WRK-00000-0001-000000000006',
    status      = 'in_progress'
WHERE ticket_number = 'MNT-2024-0001';

-- 8. Escalate overdue issues
UPDATE issues
SET status          = 'escalated',
    escalated_to    = 'USER-ADMIN-0000-0000-000000000001',
    escalated_at    = SYSTIMESTAMP,
    escalation_note = 'Deadline exceeded - auto-escalated'
WHERE status = 'pending'
  AND deadline < SYSTIMESTAMP;

-- 9. Monthly performance report
SELECT category,
       COUNT(*)                                               AS total,
       ROUND(AVG(
         (CAST(resolved_at AS DATE) - CAST(created_at AS DATE)) * 1440
       ))                                                     AS avg_minutes
FROM issues
WHERE created_at >= TRUNC(SYSTIMESTAMP, 'MM')
GROUP BY category
ORDER BY avg_minutes DESC;

-- 10. Unread notifications for a student
SELECT * FROM notifications
WHERE user_id = 'USER-STU-00000-0001-000000000002'
  AND is_read = 0
ORDER BY created_at DESC;
*/
